apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-consumer-service
  name: location-consumer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-consumer-service
  template:
    metadata:
      labels:
        service: location-consumer-service
    spec:
      containers:
      - image: location-consumer-service:1
        name: location-consumer-service
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: queue-env
              key: KAFKA_SERVER
        - name: LOCATION_TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: queue-env
              key: LOCATION_TOPIC_NAME